In [7]:
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')

In [8]:
df= pd.read_excel('height-weight.xlsx')

In [24]:
df.tail()

Gender     Height      Weight
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df.Gender = le.fit_transform(df[['Gender']])

In [11]:
x=df[['Gender', 'Height']]
y= df[['Weight']]

In [13]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [102]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [103]:
reg = LinearRegression()

In [114]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [115]:
reg.fit(x_train,y_train)


LinearRegression()

In [116]:
y_pred = reg.predict(x_test)
train_pred= reg.predict(x_train)

In [117]:
reg.coef_

array([[19.40887092,  5.97456691]])

In [118]:
reg.intercept_

array([-244.90628235])

In [119]:
reg.score(x_train,y_train)

0.8975503748409618

In [120]:
reg.score(x_test,y_test)

0.9092763639950966

In [121]:
from sklearn.metrics import mean_squared_error
mse_test= mean_squared_error(y_test,y_pred)
mse

96.83734437830608

In [122]:
mse_train= mean_squared_error(y_train,train_pred)
mse_train

104.71905723666934

In [123]:
gender = float(input("Enter gender (0 for female, 1 for male): "))
height = float(input("Enter height in inches: "))
manual_input = np.array([[gender, height]])
predicted_weight = reg.predict(manual_input)
predicted_weight

Enter gender (0 for female, 1 for male):  1
Enter height in inches:  73.814


array([[215.50927079]])

#Regression_problem

In [124]:
from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pyplot as plt

In [125]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)

In [126]:
k = 3
knn_regressor = KNeighborsRegressor(n_neighbors=k,weights='distance')

In [127]:
knn_regressor.fit(x_train, y_train)


KNeighborsRegressor(n_neighbors=3, weights='distance')

In [128]:
test_pred = knn_regressor.predict(x_test)


In [129]:
mse_test= mean_squared_error(y_test,test_pred)
mse_test

153.00740067611136

In [130]:
train_pred = knn_regressor.predict(x_train)

In [131]:
mse_train= mean_squared_error(y_train,train_pred)
mse_train

0.0

In [132]:
train_pred

array([[192.0143354],
       [151.5239473],
       [194.7495235],
       ...,
       [156.8005036],
       [179.3868167],
       [150.3805974]])

In [133]:
y_train

Weight
48    192.014335
5365  151.523947
2770  194.749524
3017  196.473754
4279  186.504349
...          ...
5734  139.223151
5191   90.728561
5390  156.800504
860   179.386817
7270  150.380597

[7699 rows x 1 columns]

In [134]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, test_pred)

In [135]:
r2

0.8533084990032029

In [136]:
import numpy as np
# Take manual input for gender and height
gender = float(input("Enter gender (0 for female, 1 for male): "))
height = float(input("Enter height in inches: "))

manual_input = np.array([[gender, height]])
predicted_weight = knn_regressor.predict(manual_input)
predicted_weight


Enter gender (0 for female, 1 for male):  1
Enter height in inches:  73.816


array([[207.49872126]])

#knn classifer

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [12]:
x=df[['Weight', 'Height']]
y= df[['Gender']]

In [13]:
knn_cls= KNeighborsClassifier(n_neighbors=3,weights='distance')

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [15]:
knn_cls.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [16]:
test_pred_c=knn_cls.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, test_pred_c)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 89.25%


In [25]:
height = float(input("Enter height in inches: "))
weight = float(input("Enter weight in lbs: "))
manual_input = [[height, weight]]

predicted_gender = knn_cls.predict(manual_input)
gender_label = "Male" if predicted_gender[0] == 1 else "Female"
gender_label

Enter height in inches:  60
Enter weight in lbs:  110


'Male'